apiVersion: apps/v1
kind: Deployment
metadata:
 name: frontend-app
spec:
 replicas: 1
 selector:
   matchLabels:
 template:
   metadata:
     labels:
   spec:
     containers:
       - name: nginx
         image: nginx:latest
         ports:
           - containerPort: 80
