apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-dev
  namespace: argocd
spec:
  project: default


  source:
    repoURL: <data>
    targetRevision: HEAD
    path: environments/dev/mongodb
  destination:
    server: https://kubernetes.default.svc
    namespace: mongo

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
