apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress-gateway
  namespace: argocd
spec:
  project: default


  source:
    repoURL: git@github.com:Miqquelangel/argocd.git
    targetRevision: HEAD
    path: apps/istioIngressGateway
  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
