apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sign-up-app-dev
  namespace: argocd
spec:
  project: default


  source:
    repoURL: git@github.com:Miqquelangel/argocd.git
    targetRevision: HEAD
    path: environments/dev/frontend-app/sign-up-app
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
