apiVersion: apps/v1
kind: Deployment
metadata:
 name: api-app
spec:
 replicas: 1
 selector:
   matchLabels:
 template:
   metadata:
     labels:
   spec:
     containers:
       - name: api-backend
         image: miqquel/miqquel-testing:api-v2
         ports:
           - containerPort: 80
