apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api

bases:
  - ../../../apps/api-app/dev

commonLabels:
  app: v1
  type: api-backend

replicas:
- name: api-app
  count: 1

namePrefix: dev-

# images:
#  - name: miqquel/miqquel-testing
#    newName: miqquel/miqquel-testing
#    newTag: api-backend

