apiVersion: apps/v1
kind: Deployment
metadata:
  name: sign-in-app
spec:
  template:
    spec:
      containers:
      - name: nginx
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: nginx-html
        configMap:
          name: nginx-config


