apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-app-prod
  namespace: argocd
spec:
  project: default


  source:
    repoURL: git@github.com:Miqquelangel/argocd.git
    targetRevision: HEAD
    path: environments/prod/api-app
  destination:
    server: https://kubernetes.default.svc
    namespace: api

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
